---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: start apache2 service
    service:
      name: apache2
      state: started

  # - name: Open port 80 for http access
  #   firewalld:
  #     service: http
  #     permanent: true
  #     state: enabled

  # - name: Restart firewalld service to load firewall changes
  #   service:
  #     name: firewalld
  #     state: reloaded

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest