---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
  
  - name: update repository index
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_distribution == "CentOS"
  
  - name: add php support for httpd
    yum:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
    when: ansible_distribution == "CentOS"

  - name: Restart firewalld service to load firewall changes
    service:
      name: firewalld
      state: reloaded
    when: ansible_distribution == "CentOS"

  