---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Debian)
    tags: always
    apt:
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php Ubuntu servers
    tags: debain,apache,php
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"
  
  - name: install apache and php CentOS servers
    tags: centos,apache.php
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,db,mariadb
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariaddb package (Debian)
    tags: debian,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"